name: build+push Docker image to Docker Hub

on:
  push:
    branches:
      - main  


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}  # Docker Hub username from GitHub Secrets
        password: ${{ secrets.DOCKER_HUB_PASS }}  # Docker Hub password from GitHub Secrets

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .  
        push: true  
        tags: ${{ secrets.DOCKER_HUB_USER }}/my-python-app:latest 

    - name: Verify Image on Docker Hub
      run: docker run --rm ${{ secrets.DOCKER_HUB_USER }}/my-python-app:latest --version  